base:
  project: base-project
  train_cols: SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
  target_col: Species

data_source:
  source: data/source/Iris.csv #Could be any remote source

processed_data:
  dataset_csv: data/processed/iris_train.csv

split_data:
  train_size: 0.888

estimators:
  lr_training:
    params:
      random_state: 42
model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json
  confusion_matrix_csv: reports/confusion_matrix.csv
  confusion_matrix_png: reports/confusion_matrix.png
  predictions: reports/predictions.csv

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: IrisExperiment
  run_name: mlops
  remote_server_uri: http://127.0.0.1:1234
